mapping:
  - name: local_name
    xpaths:
      - 'mods:identifier[@type="local"]'
      - 'mods:identifier[@type="Vendor ID"]'
      - 'mods:identifier[@type="archival number"]'
      - 'mods:identifier[@type="catalog"]'
      - 'mods:identifier[@type="circular"]'
      - 'mods:identifier[@type="cw"]'
      - 'mods:identifier[@type="document ID"]'
      - 'mods:identifier[@type="documentID"]'
      - 'mods:identifier[@type="filename"]'
      - 'mods:identifier[@type="film number"]'
      - 'mods:identifier[@type="legacy"]'
      - 'mods:identifier[@type="local"]'
      - 'mods:identifier[@type="original ID"]'
      - 'mods:identifier[@type="photograph number"]'
      - 'mods:identifier[@type="slide number"]'
      - 'mods:identifier[@type="pid"]'
      - 'mods:identifier[@type="opac"]'
      - 'mods:identifier[@type="spc"]'
    property: "http://id.loc.gov/vocabulary/identifiers/local"

  - name: acquisition_identifier
    xpaths:
      - 'mods:identifier[@type="acquisition"]'
    property: "http://opaquenamespace.org/ns/accessionNumber"

  - name: oclc
    xpaths:
      - 'mods:identifier[@type="oclc"]'
    property: "http://dbpedia.org/ontology/oclc"

  - name: issn
    xpaths:
      - 'mods:identifier[@type="issn"]'
    property: "http://dbpedia.org/ontology/issn"

  - name: isbn
    xpaths:
      - 'mods:identifier[@type="isbn"]'
    property: "http://dbpedia.org/ontology/isbn"

  - name: title_and_alternative_title
    xpaths:
      - 'mods:titleInfo[not(@supplied)]/mods:title'
      - 'mods:titleInfo[@supplied="yes"]/mods:title'
    properties:
      - "http://purl.org/dc/terms/title"
      - "http://purl.org/dc/terms/alternative"
    special: "TitleProperty"

  - name: abstract
    xpaths:
      - 'mods:abstract'
    property: "http://purl.org/dc/terms/abstract"

  - name: table_of_contents
    xpaths:
      - 'mods:tableOfContents'
    property: "http://purl.org/dc/terms/tableOfContents"

  - name: names
    xpaths:
      - 'mods:name/mods:namePart'
    properties:
      - "http://id.loc.gov/vocabulary/relators/rcp"
      - "http://id.loc.gov/vocabulary/relators/arc"
      - "http://id.loc.gov/vocabulary/relators/arr"
      - http://id.loc.gov/vocabulary/relators/art
      - http://id.loc.gov/vocabulary/relators/asn
      - http://id.loc.gov/vocabulary/relators/att
      - http://id.loc.gov/vocabulary/relators/aut
      - http://id.loc.gov/vocabulary/relators/ato
      - http://id.loc.gov/vocabulary/relators/bdd
      - http://id.loc.gov/vocabulary/relators/ctg
      - http://id.loc.gov/vocabulary/relators/cns
      - http://id.loc.gov/vocabulary/relators/chr
      - http://id.loc.gov/vocabulary/relators/cli
      - http://id.loc.gov/vocabulary/relators/com
      - http://id.loc.gov/vocabulary/relators/cmp
      - http://id.loc.gov/vocabulary/relators/ctr
      - http://id.loc.gov/vocabulary/relators/ctb
      - http://id.loc.gov/vocabulary/relators/cph
      - http://id.loc.gov/vocabulary/relators/crp
      - http://id.loc.gov/vocabulary/relators/cst
      - http://id.loc.gov/vocabulary/relators/cre
      - http://id.loc.gov/vocabulary/relators/dte
      - http://id.loc.gov/vocabulary/relators/dpc
      - http://id.loc.gov/vocabulary/relators/dsr
      - http://id.loc.gov/vocabulary/relators/dst
      - http://id.loc.gov/vocabulary/relators/dnr
      - http://id.loc.gov/vocabulary/relators/edt
      - http://id.loc.gov/vocabulary/relators/edc
      - http://id.loc.gov/vocabulary/relators/egr
      - http://id.loc.gov/vocabulary/relators/fmo
      - http://id.loc.gov/vocabulary/relators/hnr
      - http://id.loc.gov/vocabulary/relators/his
      - http://id.loc.gov/vocabulary/relators/ill
      - http://id.loc.gov/vocabulary/relators/itr
      - http://id.loc.gov/vocabulary/relators/ive
      - http://id.loc.gov/vocabulary/relators/ivr
      - http://id.loc.gov/vocabulary/relators/isb
      - http://id.loc.gov/vocabulary/relators/ltg
      - http://id.loc.gov/vocabulary/relators/lyr
      - http://id.loc.gov/vocabulary/relators/mcp
      - http://id.loc.gov/vocabulary/relators/msd
      - http://id.loc.gov/vocabulary/relators/orm
      - http://id.loc.gov/vocabulary/relators/org
      - http://id.loc.gov/vocabulary/relators/own
      - http://id.loc.gov/vocabulary/relators/prf
      - http://id.loc.gov/vocabulary/relators/pht
      - http://id.loc.gov/vocabulary/relators/prt
      - http://id.loc.gov/vocabulary/relators/pop
      - http://id.loc.gov/vocabulary/relators/pro
      - http://id.loc.gov/vocabulary/relators/prn
      - http://id.loc.gov/vocabulary/relators/pbl
      - http://id.loc.gov/vocabulary/relators/rsr
      - http://id.loc.gov/vocabulary/relators/std
      - http://id.loc.gov/vocabulary/relators/sgn
      - http://id.loc.gov/vocabulary/relators/spk
      - http://id.loc.gov/vocabulary/relators/sgd
      - http://id.loc.gov/vocabulary/relators/stm
      - http://id.loc.gov/vocabulary/relators/stn
      - http://id.loc.gov/vocabulary/relators/srv
      - http://id.loc.gov/vocabulary/relators/trl
      - http://id.loc.gov/vocabulary/relators/vdg
      - http://id.loc.gov/vocabulary/relators/wit
    special: "NameProperty"