mapping:
  - name: local_name
    xpaths:
      - 'mods:identifier[@type="local"]'
      - 'mods:identifier[@type="Vendor ID"]'
      - 'mods:identifier[@type="archival number"]'
      - 'mods:identifier[@type="catalog"]'
      - 'mods:identifier[@type="circular"]'
      - 'mods:identifier[@type="cw"]'
      - 'mods:identifier[@type="document ID"]'
      - 'mods:identifier[@type="documentID"]'
      - 'mods:identifier[@type="filename"]'
      - 'mods:identifier[@type="film number"]'
      - 'mods:identifier[@type="legacy"]'
      - 'mods:identifier[@type="local"]'
      - 'mods:identifier[@type="original ID"]'
      - 'mods:identifier[@type="photograph number"]'
      - 'mods:identifier[@type="slide number"]'
      - 'mods:identifier[@type="pid"]'
      - 'mods:identifier[@type="opac"]'
      - 'mods:identifier[@type="spc"]'
    property: "http://id.loc.gov/vocabulary/identifiers/local"

  - name: acquisition_identifier
    xpaths:
      - 'mods:identifier[@type="acquisition"]'
    property: "http://opaquenamespace.org/ns/accessionNumber"

  - name: oclc
    xpaths:
      - 'mods:identifier[@type="oclc"]'
    property: "http://dbpedia.org/ontology/oclc"

  - name: issn
    xpaths:
      - 'mods:identifier[@type="issn"]'
    property: "http://dbpedia.org/ontology/issn"

  - name: isbn
    xpaths:
      - 'mods:identifier[@type="isbn"]'
    property: "http://dbpedia.org/ontology/isbn"

  - name: title_and_alternative_title
    xpaths:
      - 'mods:titleInfo[not(@supplied)]/mods:title'
      - 'mods:titleInfo[@supplied="yes"]/mods:title'
    properties:
      - "http://purl.org/dc/terms/title"
      - "http://purl.org/dc/terms/alternative"
    special: "TitleProperty"

  - name: abstract
    xpaths:
      - 'mods:abstract'
    property: "http://purl.org/dc/terms/abstract"

  - name: table_of_contents
    xpaths:
      - 'mods:tableOfContents'
    property: "http://purl.org/dc/terms/tableOfContents"

  - name: names
    xpaths:
      - 'mods:name/mods:namePart'
    properties:
      - "http://id.loc.gov/vocabulary/relators/rcp"
    special: "NameProperty"